### PR TITLE
Use tabs and not panel

### PR DESCRIPTION
**Pull request by blackout314**
user friendly panel

### CODE REVIEW

**Comment by thundo** [comment]
Hi @blackout314
thanks for your PR, much appreciated. I'll merge right now and add a couple fixes for active tabs and the code-editor.

Thank you

**Comment by blackout314** [comment]
ok, add LICENCE file :-) i will make other fix and add (like ip check by nastyhosts)

**Comment by blackout314** [comment]
il mio inglese fa schifo :-D ripeto voglio fare altre belle aggiunte e migliorie ma solo se la licenza lo permette, quindi pubblicate la licenza ^_^

**Comment by thundo** [comment]
Thanks @blackout314. We moved this to its own ticket, #2.

**Pull request merged**
